name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pytest

    - name: Lint code
      run: |
        pip install pylint
        pylint main.py

    - name: Run tests
      run: |
        pip install pytest
        pytest

    - name: Extract short SHA
      id: vars
      run: echo "GIT_SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: darshasawa7899/fastapi-github-actions:${{ env.GIT_SHORT_SHA }}
   